/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clickitserver;

import io.github.davidg95.clickitapi.Camera;
import io.github.davidg95.clickitapi.Lens;
import io.github.davidg95.productapi.Product;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 * The dialog to create a new product.
 *
 * @author 1301480
 */
public class AddProductGUI extends javax.swing.JDialog {

    private static JDialog dialog;
    private static Product product;

    /**
     * Creates new form AddProductGUI
     */
    public AddProductGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
    }

    public static Product showAddProductDialog() {
        dialog = new AddProductGUI();

        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        product = null;

        dialog.setVisible(true);

        return product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpSensor = new javax.swing.ButtonGroup();
        btngrpProduct = new javax.swing.ButtonGroup();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblMegapixles = new javax.swing.JLabel();
        lblSensor = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtMegapixles = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        radCrop = new javax.swing.JRadioButton();
        radFull = new javax.swing.JRadioButton();
        cmdClear = new javax.swing.JButton();
        cmdAdd = new javax.swing.JButton();
        cmdClose = new javax.swing.JButton();
        radCamera = new javax.swing.JRadioButton();
        radLens = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtFocMin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFocMax = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFMin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFMax = new javax.swing.JTextField();
        chkFull = new javax.swing.JCheckBox();
        chkVR = new javax.swing.JCheckBox();
        chkMacro = new javax.swing.JCheckBox();
        chkAF = new javax.swing.JCheckBox();

        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setTitle("Add New Camera");
        setResizable(false);

        lblMake.setText("Make:");

        lblModel.setText("Model:");

        lblMegapixles.setText("Megapixles:");

        lblSensor.setText("Sensor:");

        lblStock.setText("Initial Stock:");

        lblPrice.setText("Price:");

        txtMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakeActionPerformed(evt);
            }
        });

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtMegapixles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMegapixlesActionPerformed(evt);
            }
        });

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        btngrpSensor.add(radCrop);
        radCrop.setText("Crop");

        btngrpSensor.add(radFull);
        radFull.setText("Full");

        cmdClear.setText("Clear");
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        cmdAdd.setText("Add");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        btngrpProduct.add(radCamera);
        radCamera.setText("Camera");
        radCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCameraActionPerformed(evt);
            }
        });

        btngrpProduct.add(radLens);
        radLens.setText("Lens");
        radLens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLensActionPerformed(evt);
            }
        });

        jLabel1.setText("Focal Range:");

        jLabel2.setText("-");

        jLabel3.setText("Aperture:");

        jLabel4.setText("-");

        chkFull.setText("Full Frame Format");

        chkVR.setText("Vibration Reduction");

        chkMacro.setText("Macro");

        chkAF.setText("Auto Focus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMake)
                            .addComponent(lblModel)
                            .addComponent(lblStock)
                            .addComponent(lblPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdClear)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(cmdAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                        .addComponent(cmdClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMake, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtModel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtPrice))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblMegapixles)
                            .addComponent(lblSensor)
                            .addComponent(jLabel1))
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMegapixles)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radCrop)
                                        .addGap(18, 18, 18)
                                        .addComponent(radFull)))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtFMin, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                            .addComponent(txtFocMin))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFocMax, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                            .addComponent(txtFMax)))
                                    .addComponent(chkFull, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkVR, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkMacro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkAF, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(radCamera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radLens)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCamera)
                    .addComponent(radLens))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMake)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModel)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMegapixles)
                            .addComponent(txtMegapixles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSensor)
                            .addComponent(radCrop)
                            .addComponent(radFull))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtFocMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtFocMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtFMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtFMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFull)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkVR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkMacro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdClear)
                    .addComponent(cmdAdd)
                    .addComponent(cmdClose))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to listen for the add button being pressed.
     *
     * @param evt the event of the button being pressed.
     */
    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        String make;
        String model;
        int stock;
        double price;

        double megapixles;
        boolean full;

        int min_mm;
        int max_mm;
        double min_f;
        double max_f;
        boolean isFull;
        boolean hasVR;
        boolean isMacro;
        boolean hasAF;

        try {
            if (radCamera.isSelected()) {
                make = this.txtMake.getText();
                model = this.txtModel.getText();
                megapixles = Double.parseDouble(this.txtMegapixles.getText());
                full = this.radFull.isSelected();
                stock = Integer.parseInt(this.txtStock.getText());
                price = Double.parseDouble(this.txtPrice.getText());

                product = new Camera(make, make + " " + model, megapixles, full, stock, price);

                this.setVisible(false);
            } else if (radLens.isSelected()) {
                make = this.txtMake.getText();
                stock = Integer.parseInt(this.txtStock.getText());
                price = Double.parseDouble(this.txtPrice.getText());
                
                min_mm = Integer.parseInt(txtFocMin.getText());
                max_mm = Integer.parseInt(txtFocMax.getText());
                min_f = Double.parseDouble(txtFMin.getText());
                max_f = Double.parseDouble(txtFMax.getText());
                isFull = this.chkFull.isSelected();
                hasVR = this.chkVR.isSelected();
                isMacro = this.chkMacro.isSelected();
                hasAF = this.chkAF.isSelected();
                
                product = new Lens(make, min_mm, max_mm, min_f, max_f, isFull, hasVR, isMacro, hasAF, price, stock);
                
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Some fields were left blank or have not been filled in correctly");
        }
    }//GEN-LAST:event_cmdAddActionPerformed

    /**
     * Method to listen for the close button being pressed.
     *
     * @param evt the event of the button being pressed.
     */
    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed

    /**
     * Method to listen for the clear button being pressed.
     *
     * @param evt the event of the clear button being pressed.
     */
    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        this.txtMake.setText(null);
        this.txtModel.setText(null);
        this.txtMegapixles.setText(null);
        if (radCrop.isSelected()) {
            radCrop.setSelected(false);
        }
        if (radFull.isSelected()) {
            radFull.setSelected(false);
        }
        this.txtStock.setText(null);
        this.txtPrice.setText(null);
    }//GEN-LAST:event_cmdClearActionPerformed

    private void txtMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakeActionPerformed
        cmdAdd.doClick();
    }//GEN-LAST:event_txtMakeActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        cmdAdd.doClick();
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtMegapixlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMegapixlesActionPerformed
        cmdAdd.doClick();
    }//GEN-LAST:event_txtMegapixlesActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        cmdAdd.doClick();
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        cmdAdd.doClick();
    }//GEN-LAST:event_txtPriceActionPerformed

    private void radCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCameraActionPerformed
        txtMegapixles.setEnabled(true);
        radCrop.setEnabled(true);
        radFull.setEnabled(true);
        txtModel.setEnabled(true);
        txtFocMin.setEnabled(false);
        txtFocMax.setEnabled(false);
        txtFMin.setEnabled(false);
        txtFMax.setEnabled(false);
        chkFull.setEnabled(false);
        chkVR.setEnabled(false);
        chkMacro.setEnabled(false);
        chkAF.setEnabled(false);
    }//GEN-LAST:event_radCameraActionPerformed

    private void radLensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLensActionPerformed
        txtMegapixles.setEnabled(false);
        radCrop.setEnabled(false);
        radFull.setEnabled(false);
        txtModel.setEnabled(false);
        txtFocMin.setEnabled(true);
        txtFocMax.setEnabled(true);
        txtFMin.setEnabled(true);
        txtFMax.setEnabled(true);
        chkFull.setEnabled(true);
        chkVR.setEnabled(true);
        chkMacro.setEnabled(true);
        chkAF.setEnabled(true);
    }//GEN-LAST:event_radLensActionPerformed

    /**
     * Method to close the form.
     */
    private void closeForm() {
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpProduct;
    private javax.swing.ButtonGroup btngrpSensor;
    private javax.swing.JCheckBox chkAF;
    private javax.swing.JCheckBox chkFull;
    private javax.swing.JCheckBox chkMacro;
    private javax.swing.JCheckBox chkVR;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblMegapixles;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSensor;
    private javax.swing.JLabel lblStock;
    private javax.swing.JRadioButton radCamera;
    private javax.swing.JRadioButton radCrop;
    private javax.swing.JRadioButton radFull;
    private javax.swing.JRadioButton radLens;
    private javax.swing.JTextField txtFMax;
    private javax.swing.JTextField txtFMin;
    private javax.swing.JTextField txtFocMax;
    private javax.swing.JTextField txtFocMin;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMegapixles;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
