/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clickitserver;

import io.github.davidg95.productapi.Product;
import io.github.davidg95.productapi.ProductNotFoundException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class ProductListWindow extends javax.swing.JFrame {

    private static JFrame frame;

    private final Data data;

    /**
     * Creates new form ProductListWindow
     *
     * @param data List of products to show.
     */
    public ProductListWindow(Data data) {
        this.data = data;
        initComponents();
        updateList();
    }

    /**
     * Method to update the list.
     */
    public final void updateList() {

        lstProducts.removeAll();

        List<Product> products = data.getAllProducts();

        String[] items = new String[products.size()];

        for (int i = 0; i <= (items.length - 1); i++) {
            items[i] = "<html><pre>" + products.get(i).getCode() + "\t\t" + products.get(i).getName() + ((products.get(i).getName()).length() < 17 ? "\t\t" : "\t") + products.get(i).getStock() + "\t" + products.get(i).getPrice() + "</pre></html>";
        }

        lstProducts.setListData(items);
    }

    /**
     * Method to show the list of products.
     *
     * @param data List of products.
     */
    public static void showProductListWindow(Data data) {
        frame = new ProductListWindow(data);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstProducts = new javax.swing.JList();
        btnAddProduct = new javax.swing.JButton();
        btnRemoveProduct = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Products");

        lstProducts.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstProducts);

        btnAddProduct.setText("Add New Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnRemoveProduct.setText("Remove Product");
        btnRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnRemoveProduct)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        Product product = AddProductGUI.showAddProductDialog();
        if (product != null) {
            data.addProduct(product);
            updateList();
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductActionPerformed
        if (lstProducts.getSelectedIndex() != -1) {
            Product p = data.getAllProducts().get(lstProducts.getSelectedIndex());
            if (JOptionPane.showConfirmDialog(this, "Are you sure you want to remove product " + p.getCode() + "?", "Remove Product", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    data.deleteProduct(p.getCode());
                    updateList();
                } catch (ProductNotFoundException ex) {

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select a product", "Delete Product", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstProducts;
    // End of variables declaration//GEN-END:variables
}
